// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package echofarmrpc

import (
	"context"
	"fmt"
)

type RelayRequest struct {
	RequestId   string  `thrift:"request_id,1,required" frugal:"1,required,string" json:"request_id"`
	Token       string  `thrift:"token,2,required" frugal:"2,required,string" json:"token"`
	Query       *string `thrift:"query,3,optional" frugal:"3,optional,string" json:"query,omitempty"`
	Body        []byte  `thrift:"body,4,optional" frugal:"4,optional,binary" json:"body,omitempty"`
	ContentType *string `thrift:"content_type,5,optional" frugal:"5,optional,string" json:"content_type,omitempty"`
}

func NewRelayRequest() *RelayRequest {
	return &RelayRequest{}
}

func (p *RelayRequest) InitDefault() {
}

func (p *RelayRequest) GetRequestId() (v string) {
	return p.RequestId
}

func (p *RelayRequest) GetToken() (v string) {
	return p.Token
}

var RelayRequest_Query_DEFAULT string

func (p *RelayRequest) GetQuery() (v string) {
	if !p.IsSetQuery() {
		return RelayRequest_Query_DEFAULT
	}
	return *p.Query
}

var RelayRequest_Body_DEFAULT []byte

func (p *RelayRequest) GetBody() (v []byte) {
	if !p.IsSetBody() {
		return RelayRequest_Body_DEFAULT
	}
	return p.Body
}

var RelayRequest_ContentType_DEFAULT string

func (p *RelayRequest) GetContentType() (v string) {
	if !p.IsSetContentType() {
		return RelayRequest_ContentType_DEFAULT
	}
	return *p.ContentType
}
func (p *RelayRequest) SetRequestId(val string) {
	p.RequestId = val
}
func (p *RelayRequest) SetToken(val string) {
	p.Token = val
}
func (p *RelayRequest) SetQuery(val *string) {
	p.Query = val
}
func (p *RelayRequest) SetBody(val []byte) {
	p.Body = val
}
func (p *RelayRequest) SetContentType(val *string) {
	p.ContentType = val
}

func (p *RelayRequest) IsSetQuery() bool {
	return p.Query != nil
}

func (p *RelayRequest) IsSetBody() bool {
	return p.Body != nil
}

func (p *RelayRequest) IsSetContentType() bool {
	return p.ContentType != nil
}

func (p *RelayRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RelayRequest(%+v)", *p)
}

var fieldIDToName_RelayRequest = map[int16]string{
	1: "request_id",
	2: "token",
	3: "query",
	4: "body",
	5: "content_type",
}

type RelayResponse struct {
	RequestId   string `thrift:"request_id,1,required" frugal:"1,required,string" json:"request_id"`
	StatusCode  int32  `thrift:"status_code,2,required" frugal:"2,required,i32" json:"status_code"`
	ContentType string `thrift:"content_type,3,required" frugal:"3,required,string" json:"content_type"`
	Body        []byte `thrift:"body,4,required" frugal:"4,required,binary" json:"body"`
}

func NewRelayResponse() *RelayResponse {
	return &RelayResponse{}
}

func (p *RelayResponse) InitDefault() {
}

func (p *RelayResponse) GetRequestId() (v string) {
	return p.RequestId
}

func (p *RelayResponse) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *RelayResponse) GetContentType() (v string) {
	return p.ContentType
}

func (p *RelayResponse) GetBody() (v []byte) {
	return p.Body
}
func (p *RelayResponse) SetRequestId(val string) {
	p.RequestId = val
}
func (p *RelayResponse) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *RelayResponse) SetContentType(val string) {
	p.ContentType = val
}
func (p *RelayResponse) SetBody(val []byte) {
	p.Body = val
}

func (p *RelayResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RelayResponse(%+v)", *p)
}

var fieldIDToName_RelayResponse = map[int16]string{
	1: "request_id",
	2: "status_code",
	3: "content_type",
	4: "body",
}

type EchoFarmGateway interface {
	Health(ctx context.Context, request *RelayRequest) (r *RelayResponse, err error)

	Learn(ctx context.Context, request *RelayRequest) (r *RelayResponse, err error)

	NextAction(ctx context.Context, request *RelayRequest) (r *RelayResponse, err error)

	ActionResult_(ctx context.Context, request *RelayRequest) (r *RelayResponse, err error)

	Correction(ctx context.Context, request *RelayRequest) (r *RelayResponse, err error)

	PlayerModel(ctx context.Context, request *RelayRequest) (r *RelayResponse, err error)

	Skill(ctx context.Context, request *RelayRequest) (r *RelayResponse, err error)

	Memory(ctx context.Context, request *RelayRequest) (r *RelayResponse, err error)

	ModelUsage(ctx context.Context, request *RelayRequest) (r *RelayResponse, err error)
}

type EchoFarmGatewayHealthArgs struct {
	Request *RelayRequest `thrift:"request,1" frugal:"1,default,RelayRequest" json:"request"`
}

func NewEchoFarmGatewayHealthArgs() *EchoFarmGatewayHealthArgs {
	return &EchoFarmGatewayHealthArgs{}
}

func (p *EchoFarmGatewayHealthArgs) InitDefault() {
}

var EchoFarmGatewayHealthArgs_Request_DEFAULT *RelayRequest

func (p *EchoFarmGatewayHealthArgs) GetRequest() (v *RelayRequest) {
	if !p.IsSetRequest() {
		return EchoFarmGatewayHealthArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *EchoFarmGatewayHealthArgs) SetRequest(val *RelayRequest) {
	p.Request = val
}

func (p *EchoFarmGatewayHealthArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *EchoFarmGatewayHealthArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayHealthArgs(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayHealthArgs = map[int16]string{
	1: "request",
}

type EchoFarmGatewayHealthResult struct {
	Success *RelayResponse `thrift:"success,0,optional" frugal:"0,optional,RelayResponse" json:"success,omitempty"`
}

func NewEchoFarmGatewayHealthResult() *EchoFarmGatewayHealthResult {
	return &EchoFarmGatewayHealthResult{}
}

func (p *EchoFarmGatewayHealthResult) InitDefault() {
}

var EchoFarmGatewayHealthResult_Success_DEFAULT *RelayResponse

func (p *EchoFarmGatewayHealthResult) GetSuccess() (v *RelayResponse) {
	if !p.IsSetSuccess() {
		return EchoFarmGatewayHealthResult_Success_DEFAULT
	}
	return p.Success
}
func (p *EchoFarmGatewayHealthResult) SetSuccess(x interface{}) {
	p.Success = x.(*RelayResponse)
}

func (p *EchoFarmGatewayHealthResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoFarmGatewayHealthResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayHealthResult(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayHealthResult = map[int16]string{
	0: "success",
}

type EchoFarmGatewayLearnArgs struct {
	Request *RelayRequest `thrift:"request,1" frugal:"1,default,RelayRequest" json:"request"`
}

func NewEchoFarmGatewayLearnArgs() *EchoFarmGatewayLearnArgs {
	return &EchoFarmGatewayLearnArgs{}
}

func (p *EchoFarmGatewayLearnArgs) InitDefault() {
}

var EchoFarmGatewayLearnArgs_Request_DEFAULT *RelayRequest

func (p *EchoFarmGatewayLearnArgs) GetRequest() (v *RelayRequest) {
	if !p.IsSetRequest() {
		return EchoFarmGatewayLearnArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *EchoFarmGatewayLearnArgs) SetRequest(val *RelayRequest) {
	p.Request = val
}

func (p *EchoFarmGatewayLearnArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *EchoFarmGatewayLearnArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayLearnArgs(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayLearnArgs = map[int16]string{
	1: "request",
}

type EchoFarmGatewayLearnResult struct {
	Success *RelayResponse `thrift:"success,0,optional" frugal:"0,optional,RelayResponse" json:"success,omitempty"`
}

func NewEchoFarmGatewayLearnResult() *EchoFarmGatewayLearnResult {
	return &EchoFarmGatewayLearnResult{}
}

func (p *EchoFarmGatewayLearnResult) InitDefault() {
}

var EchoFarmGatewayLearnResult_Success_DEFAULT *RelayResponse

func (p *EchoFarmGatewayLearnResult) GetSuccess() (v *RelayResponse) {
	if !p.IsSetSuccess() {
		return EchoFarmGatewayLearnResult_Success_DEFAULT
	}
	return p.Success
}
func (p *EchoFarmGatewayLearnResult) SetSuccess(x interface{}) {
	p.Success = x.(*RelayResponse)
}

func (p *EchoFarmGatewayLearnResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoFarmGatewayLearnResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayLearnResult(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayLearnResult = map[int16]string{
	0: "success",
}

type EchoFarmGatewayNextActionArgs struct {
	Request *RelayRequest `thrift:"request,1" frugal:"1,default,RelayRequest" json:"request"`
}

func NewEchoFarmGatewayNextActionArgs() *EchoFarmGatewayNextActionArgs {
	return &EchoFarmGatewayNextActionArgs{}
}

func (p *EchoFarmGatewayNextActionArgs) InitDefault() {
}

var EchoFarmGatewayNextActionArgs_Request_DEFAULT *RelayRequest

func (p *EchoFarmGatewayNextActionArgs) GetRequest() (v *RelayRequest) {
	if !p.IsSetRequest() {
		return EchoFarmGatewayNextActionArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *EchoFarmGatewayNextActionArgs) SetRequest(val *RelayRequest) {
	p.Request = val
}

func (p *EchoFarmGatewayNextActionArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *EchoFarmGatewayNextActionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayNextActionArgs(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayNextActionArgs = map[int16]string{
	1: "request",
}

type EchoFarmGatewayNextActionResult struct {
	Success *RelayResponse `thrift:"success,0,optional" frugal:"0,optional,RelayResponse" json:"success,omitempty"`
}

func NewEchoFarmGatewayNextActionResult() *EchoFarmGatewayNextActionResult {
	return &EchoFarmGatewayNextActionResult{}
}

func (p *EchoFarmGatewayNextActionResult) InitDefault() {
}

var EchoFarmGatewayNextActionResult_Success_DEFAULT *RelayResponse

func (p *EchoFarmGatewayNextActionResult) GetSuccess() (v *RelayResponse) {
	if !p.IsSetSuccess() {
		return EchoFarmGatewayNextActionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *EchoFarmGatewayNextActionResult) SetSuccess(x interface{}) {
	p.Success = x.(*RelayResponse)
}

func (p *EchoFarmGatewayNextActionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoFarmGatewayNextActionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayNextActionResult(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayNextActionResult = map[int16]string{
	0: "success",
}

type EchoFarmGatewayActionResultArgs struct {
	Request *RelayRequest `thrift:"request,1" frugal:"1,default,RelayRequest" json:"request"`
}

func NewEchoFarmGatewayActionResultArgs() *EchoFarmGatewayActionResultArgs {
	return &EchoFarmGatewayActionResultArgs{}
}

func (p *EchoFarmGatewayActionResultArgs) InitDefault() {
}

var EchoFarmGatewayActionResultArgs_Request_DEFAULT *RelayRequest

func (p *EchoFarmGatewayActionResultArgs) GetRequest() (v *RelayRequest) {
	if !p.IsSetRequest() {
		return EchoFarmGatewayActionResultArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *EchoFarmGatewayActionResultArgs) SetRequest(val *RelayRequest) {
	p.Request = val
}

func (p *EchoFarmGatewayActionResultArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *EchoFarmGatewayActionResultArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayActionResultArgs(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayActionResultArgs = map[int16]string{
	1: "request",
}

type EchoFarmGatewayActionResultResult struct {
	Success *RelayResponse `thrift:"success,0,optional" frugal:"0,optional,RelayResponse" json:"success,omitempty"`
}

func NewEchoFarmGatewayActionResultResult() *EchoFarmGatewayActionResultResult {
	return &EchoFarmGatewayActionResultResult{}
}

func (p *EchoFarmGatewayActionResultResult) InitDefault() {
}

var EchoFarmGatewayActionResultResult_Success_DEFAULT *RelayResponse

func (p *EchoFarmGatewayActionResultResult) GetSuccess() (v *RelayResponse) {
	if !p.IsSetSuccess() {
		return EchoFarmGatewayActionResultResult_Success_DEFAULT
	}
	return p.Success
}
func (p *EchoFarmGatewayActionResultResult) SetSuccess(x interface{}) {
	p.Success = x.(*RelayResponse)
}

func (p *EchoFarmGatewayActionResultResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoFarmGatewayActionResultResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayActionResultResult(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayActionResultResult = map[int16]string{
	0: "success",
}

type EchoFarmGatewayCorrectionArgs struct {
	Request *RelayRequest `thrift:"request,1" frugal:"1,default,RelayRequest" json:"request"`
}

func NewEchoFarmGatewayCorrectionArgs() *EchoFarmGatewayCorrectionArgs {
	return &EchoFarmGatewayCorrectionArgs{}
}

func (p *EchoFarmGatewayCorrectionArgs) InitDefault() {
}

var EchoFarmGatewayCorrectionArgs_Request_DEFAULT *RelayRequest

func (p *EchoFarmGatewayCorrectionArgs) GetRequest() (v *RelayRequest) {
	if !p.IsSetRequest() {
		return EchoFarmGatewayCorrectionArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *EchoFarmGatewayCorrectionArgs) SetRequest(val *RelayRequest) {
	p.Request = val
}

func (p *EchoFarmGatewayCorrectionArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *EchoFarmGatewayCorrectionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayCorrectionArgs(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayCorrectionArgs = map[int16]string{
	1: "request",
}

type EchoFarmGatewayCorrectionResult struct {
	Success *RelayResponse `thrift:"success,0,optional" frugal:"0,optional,RelayResponse" json:"success,omitempty"`
}

func NewEchoFarmGatewayCorrectionResult() *EchoFarmGatewayCorrectionResult {
	return &EchoFarmGatewayCorrectionResult{}
}

func (p *EchoFarmGatewayCorrectionResult) InitDefault() {
}

var EchoFarmGatewayCorrectionResult_Success_DEFAULT *RelayResponse

func (p *EchoFarmGatewayCorrectionResult) GetSuccess() (v *RelayResponse) {
	if !p.IsSetSuccess() {
		return EchoFarmGatewayCorrectionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *EchoFarmGatewayCorrectionResult) SetSuccess(x interface{}) {
	p.Success = x.(*RelayResponse)
}

func (p *EchoFarmGatewayCorrectionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoFarmGatewayCorrectionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayCorrectionResult(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayCorrectionResult = map[int16]string{
	0: "success",
}

type EchoFarmGatewayPlayerModelArgs struct {
	Request *RelayRequest `thrift:"request,1" frugal:"1,default,RelayRequest" json:"request"`
}

func NewEchoFarmGatewayPlayerModelArgs() *EchoFarmGatewayPlayerModelArgs {
	return &EchoFarmGatewayPlayerModelArgs{}
}

func (p *EchoFarmGatewayPlayerModelArgs) InitDefault() {
}

var EchoFarmGatewayPlayerModelArgs_Request_DEFAULT *RelayRequest

func (p *EchoFarmGatewayPlayerModelArgs) GetRequest() (v *RelayRequest) {
	if !p.IsSetRequest() {
		return EchoFarmGatewayPlayerModelArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *EchoFarmGatewayPlayerModelArgs) SetRequest(val *RelayRequest) {
	p.Request = val
}

func (p *EchoFarmGatewayPlayerModelArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *EchoFarmGatewayPlayerModelArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayPlayerModelArgs(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayPlayerModelArgs = map[int16]string{
	1: "request",
}

type EchoFarmGatewayPlayerModelResult struct {
	Success *RelayResponse `thrift:"success,0,optional" frugal:"0,optional,RelayResponse" json:"success,omitempty"`
}

func NewEchoFarmGatewayPlayerModelResult() *EchoFarmGatewayPlayerModelResult {
	return &EchoFarmGatewayPlayerModelResult{}
}

func (p *EchoFarmGatewayPlayerModelResult) InitDefault() {
}

var EchoFarmGatewayPlayerModelResult_Success_DEFAULT *RelayResponse

func (p *EchoFarmGatewayPlayerModelResult) GetSuccess() (v *RelayResponse) {
	if !p.IsSetSuccess() {
		return EchoFarmGatewayPlayerModelResult_Success_DEFAULT
	}
	return p.Success
}
func (p *EchoFarmGatewayPlayerModelResult) SetSuccess(x interface{}) {
	p.Success = x.(*RelayResponse)
}

func (p *EchoFarmGatewayPlayerModelResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoFarmGatewayPlayerModelResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayPlayerModelResult(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayPlayerModelResult = map[int16]string{
	0: "success",
}

type EchoFarmGatewaySkillArgs struct {
	Request *RelayRequest `thrift:"request,1" frugal:"1,default,RelayRequest" json:"request"`
}

func NewEchoFarmGatewaySkillArgs() *EchoFarmGatewaySkillArgs {
	return &EchoFarmGatewaySkillArgs{}
}

func (p *EchoFarmGatewaySkillArgs) InitDefault() {
}

var EchoFarmGatewaySkillArgs_Request_DEFAULT *RelayRequest

func (p *EchoFarmGatewaySkillArgs) GetRequest() (v *RelayRequest) {
	if !p.IsSetRequest() {
		return EchoFarmGatewaySkillArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *EchoFarmGatewaySkillArgs) SetRequest(val *RelayRequest) {
	p.Request = val
}

func (p *EchoFarmGatewaySkillArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *EchoFarmGatewaySkillArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewaySkillArgs(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewaySkillArgs = map[int16]string{
	1: "request",
}

type EchoFarmGatewaySkillResult struct {
	Success *RelayResponse `thrift:"success,0,optional" frugal:"0,optional,RelayResponse" json:"success,omitempty"`
}

func NewEchoFarmGatewaySkillResult() *EchoFarmGatewaySkillResult {
	return &EchoFarmGatewaySkillResult{}
}

func (p *EchoFarmGatewaySkillResult) InitDefault() {
}

var EchoFarmGatewaySkillResult_Success_DEFAULT *RelayResponse

func (p *EchoFarmGatewaySkillResult) GetSuccess() (v *RelayResponse) {
	if !p.IsSetSuccess() {
		return EchoFarmGatewaySkillResult_Success_DEFAULT
	}
	return p.Success
}
func (p *EchoFarmGatewaySkillResult) SetSuccess(x interface{}) {
	p.Success = x.(*RelayResponse)
}

func (p *EchoFarmGatewaySkillResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoFarmGatewaySkillResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewaySkillResult(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewaySkillResult = map[int16]string{
	0: "success",
}

type EchoFarmGatewayMemoryArgs struct {
	Request *RelayRequest `thrift:"request,1" frugal:"1,default,RelayRequest" json:"request"`
}

func NewEchoFarmGatewayMemoryArgs() *EchoFarmGatewayMemoryArgs {
	return &EchoFarmGatewayMemoryArgs{}
}

func (p *EchoFarmGatewayMemoryArgs) InitDefault() {
}

var EchoFarmGatewayMemoryArgs_Request_DEFAULT *RelayRequest

func (p *EchoFarmGatewayMemoryArgs) GetRequest() (v *RelayRequest) {
	if !p.IsSetRequest() {
		return EchoFarmGatewayMemoryArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *EchoFarmGatewayMemoryArgs) SetRequest(val *RelayRequest) {
	p.Request = val
}

func (p *EchoFarmGatewayMemoryArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *EchoFarmGatewayMemoryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayMemoryArgs(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayMemoryArgs = map[int16]string{
	1: "request",
}

type EchoFarmGatewayMemoryResult struct {
	Success *RelayResponse `thrift:"success,0,optional" frugal:"0,optional,RelayResponse" json:"success,omitempty"`
}

func NewEchoFarmGatewayMemoryResult() *EchoFarmGatewayMemoryResult {
	return &EchoFarmGatewayMemoryResult{}
}

func (p *EchoFarmGatewayMemoryResult) InitDefault() {
}

var EchoFarmGatewayMemoryResult_Success_DEFAULT *RelayResponse

func (p *EchoFarmGatewayMemoryResult) GetSuccess() (v *RelayResponse) {
	if !p.IsSetSuccess() {
		return EchoFarmGatewayMemoryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *EchoFarmGatewayMemoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*RelayResponse)
}

func (p *EchoFarmGatewayMemoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoFarmGatewayMemoryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayMemoryResult(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayMemoryResult = map[int16]string{
	0: "success",
}

type EchoFarmGatewayModelUsageArgs struct {
	Request *RelayRequest `thrift:"request,1" frugal:"1,default,RelayRequest" json:"request"`
}

func NewEchoFarmGatewayModelUsageArgs() *EchoFarmGatewayModelUsageArgs {
	return &EchoFarmGatewayModelUsageArgs{}
}

func (p *EchoFarmGatewayModelUsageArgs) InitDefault() {
}

var EchoFarmGatewayModelUsageArgs_Request_DEFAULT *RelayRequest

func (p *EchoFarmGatewayModelUsageArgs) GetRequest() (v *RelayRequest) {
	if !p.IsSetRequest() {
		return EchoFarmGatewayModelUsageArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *EchoFarmGatewayModelUsageArgs) SetRequest(val *RelayRequest) {
	p.Request = val
}

func (p *EchoFarmGatewayModelUsageArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *EchoFarmGatewayModelUsageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayModelUsageArgs(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayModelUsageArgs = map[int16]string{
	1: "request",
}

type EchoFarmGatewayModelUsageResult struct {
	Success *RelayResponse `thrift:"success,0,optional" frugal:"0,optional,RelayResponse" json:"success,omitempty"`
}

func NewEchoFarmGatewayModelUsageResult() *EchoFarmGatewayModelUsageResult {
	return &EchoFarmGatewayModelUsageResult{}
}

func (p *EchoFarmGatewayModelUsageResult) InitDefault() {
}

var EchoFarmGatewayModelUsageResult_Success_DEFAULT *RelayResponse

func (p *EchoFarmGatewayModelUsageResult) GetSuccess() (v *RelayResponse) {
	if !p.IsSetSuccess() {
		return EchoFarmGatewayModelUsageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *EchoFarmGatewayModelUsageResult) SetSuccess(x interface{}) {
	p.Success = x.(*RelayResponse)
}

func (p *EchoFarmGatewayModelUsageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoFarmGatewayModelUsageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoFarmGatewayModelUsageResult(%+v)", *p)
}

var fieldIDToName_EchoFarmGatewayModelUsageResult = map[int16]string{
	0: "success",
}
