// Code generated by Kitex v0.16.3. DO NOT EDIT.

package echofarmgateway

import (
	"context"
	echofarmrpc "github.com/Zhang-986/Stardew-Sage/echofarm-core/kitex_gen/echofarmrpc"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Health(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error)
	Learn(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error)
	NextAction(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error)
	ActionResult_(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error)
	Correction(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error)
	PlayerModel(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error)
	Skill(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error)
	Memory(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error)
	ModelUsage(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kEchoFarmGatewayClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kEchoFarmGatewayClient struct {
	*kClient
}

func (p *kEchoFarmGatewayClient) Health(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Health(ctx, request)
}

func (p *kEchoFarmGatewayClient) Learn(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Learn(ctx, request)
}

func (p *kEchoFarmGatewayClient) NextAction(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.NextAction(ctx, request)
}

func (p *kEchoFarmGatewayClient) ActionResult_(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ActionResult_(ctx, request)
}

func (p *kEchoFarmGatewayClient) Correction(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Correction(ctx, request)
}

func (p *kEchoFarmGatewayClient) PlayerModel(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PlayerModel(ctx, request)
}

func (p *kEchoFarmGatewayClient) Skill(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Skill(ctx, request)
}

func (p *kEchoFarmGatewayClient) Memory(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Memory(ctx, request)
}

func (p *kEchoFarmGatewayClient) ModelUsage(ctx context.Context, request *echofarmrpc.RelayRequest, callOptions ...callopt.Option) (r *echofarmrpc.RelayResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ModelUsage(ctx, request)
}
