// Code generated by Kitex v0.16.3. DO NOT EDIT.

package echofarmgateway

import (
	"context"
	"errors"
	echofarmrpc "github.com/Zhang-986/Stardew-Sage/echofarm-core/kitex_gen/echofarmrpc"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Health": kitex.NewMethodInfo(
		healthHandler,
		newEchoFarmGatewayHealthArgs,
		newEchoFarmGatewayHealthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Learn": kitex.NewMethodInfo(
		learnHandler,
		newEchoFarmGatewayLearnArgs,
		newEchoFarmGatewayLearnResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"NextAction": kitex.NewMethodInfo(
		nextActionHandler,
		newEchoFarmGatewayNextActionArgs,
		newEchoFarmGatewayNextActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ActionResult": kitex.NewMethodInfo(
		actionResult_Handler,
		newEchoFarmGatewayActionResultArgs,
		newEchoFarmGatewayActionResultResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Correction": kitex.NewMethodInfo(
		correctionHandler,
		newEchoFarmGatewayCorrectionArgs,
		newEchoFarmGatewayCorrectionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PlayerModel": kitex.NewMethodInfo(
		playerModelHandler,
		newEchoFarmGatewayPlayerModelArgs,
		newEchoFarmGatewayPlayerModelResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Skill": kitex.NewMethodInfo(
		skillHandler,
		newEchoFarmGatewaySkillArgs,
		newEchoFarmGatewaySkillResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Memory": kitex.NewMethodInfo(
		memoryHandler,
		newEchoFarmGatewayMemoryArgs,
		newEchoFarmGatewayMemoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ModelUsage": kitex.NewMethodInfo(
		modelUsageHandler,
		newEchoFarmGatewayModelUsageArgs,
		newEchoFarmGatewayModelUsageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	echoFarmGatewayServiceInfo                = NewServiceInfo()
	echoFarmGatewayServiceInfoForClient       = NewServiceInfoForClient()
	echoFarmGatewayServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return echoFarmGatewayServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return echoFarmGatewayServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return echoFarmGatewayServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "EchoFarmGateway"
	handlerType := (*echofarmrpc.EchoFarmGateway)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "echofarmrpc",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*echofarmrpc.EchoFarmGatewayHealthArgs)
	realResult := result.(*echofarmrpc.EchoFarmGatewayHealthResult)
	success, err := handler.(echofarmrpc.EchoFarmGateway).Health(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEchoFarmGatewayHealthArgs() interface{} {
	return echofarmrpc.NewEchoFarmGatewayHealthArgs()
}

func newEchoFarmGatewayHealthResult() interface{} {
	return echofarmrpc.NewEchoFarmGatewayHealthResult()
}

func learnHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*echofarmrpc.EchoFarmGatewayLearnArgs)
	realResult := result.(*echofarmrpc.EchoFarmGatewayLearnResult)
	success, err := handler.(echofarmrpc.EchoFarmGateway).Learn(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEchoFarmGatewayLearnArgs() interface{} {
	return echofarmrpc.NewEchoFarmGatewayLearnArgs()
}

func newEchoFarmGatewayLearnResult() interface{} {
	return echofarmrpc.NewEchoFarmGatewayLearnResult()
}

func nextActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*echofarmrpc.EchoFarmGatewayNextActionArgs)
	realResult := result.(*echofarmrpc.EchoFarmGatewayNextActionResult)
	success, err := handler.(echofarmrpc.EchoFarmGateway).NextAction(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEchoFarmGatewayNextActionArgs() interface{} {
	return echofarmrpc.NewEchoFarmGatewayNextActionArgs()
}

func newEchoFarmGatewayNextActionResult() interface{} {
	return echofarmrpc.NewEchoFarmGatewayNextActionResult()
}

func actionResult_Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*echofarmrpc.EchoFarmGatewayActionResultArgs)
	realResult := result.(*echofarmrpc.EchoFarmGatewayActionResultResult)
	success, err := handler.(echofarmrpc.EchoFarmGateway).ActionResult_(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEchoFarmGatewayActionResultArgs() interface{} {
	return echofarmrpc.NewEchoFarmGatewayActionResultArgs()
}

func newEchoFarmGatewayActionResultResult() interface{} {
	return echofarmrpc.NewEchoFarmGatewayActionResultResult()
}

func correctionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*echofarmrpc.EchoFarmGatewayCorrectionArgs)
	realResult := result.(*echofarmrpc.EchoFarmGatewayCorrectionResult)
	success, err := handler.(echofarmrpc.EchoFarmGateway).Correction(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEchoFarmGatewayCorrectionArgs() interface{} {
	return echofarmrpc.NewEchoFarmGatewayCorrectionArgs()
}

func newEchoFarmGatewayCorrectionResult() interface{} {
	return echofarmrpc.NewEchoFarmGatewayCorrectionResult()
}

func playerModelHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*echofarmrpc.EchoFarmGatewayPlayerModelArgs)
	realResult := result.(*echofarmrpc.EchoFarmGatewayPlayerModelResult)
	success, err := handler.(echofarmrpc.EchoFarmGateway).PlayerModel(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEchoFarmGatewayPlayerModelArgs() interface{} {
	return echofarmrpc.NewEchoFarmGatewayPlayerModelArgs()
}

func newEchoFarmGatewayPlayerModelResult() interface{} {
	return echofarmrpc.NewEchoFarmGatewayPlayerModelResult()
}

func skillHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*echofarmrpc.EchoFarmGatewaySkillArgs)
	realResult := result.(*echofarmrpc.EchoFarmGatewaySkillResult)
	success, err := handler.(echofarmrpc.EchoFarmGateway).Skill(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEchoFarmGatewaySkillArgs() interface{} {
	return echofarmrpc.NewEchoFarmGatewaySkillArgs()
}

func newEchoFarmGatewaySkillResult() interface{} {
	return echofarmrpc.NewEchoFarmGatewaySkillResult()
}

func memoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*echofarmrpc.EchoFarmGatewayMemoryArgs)
	realResult := result.(*echofarmrpc.EchoFarmGatewayMemoryResult)
	success, err := handler.(echofarmrpc.EchoFarmGateway).Memory(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEchoFarmGatewayMemoryArgs() interface{} {
	return echofarmrpc.NewEchoFarmGatewayMemoryArgs()
}

func newEchoFarmGatewayMemoryResult() interface{} {
	return echofarmrpc.NewEchoFarmGatewayMemoryResult()
}

func modelUsageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*echofarmrpc.EchoFarmGatewayModelUsageArgs)
	realResult := result.(*echofarmrpc.EchoFarmGatewayModelUsageResult)
	success, err := handler.(echofarmrpc.EchoFarmGateway).ModelUsage(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEchoFarmGatewayModelUsageArgs() interface{} {
	return echofarmrpc.NewEchoFarmGatewayModelUsageArgs()
}

func newEchoFarmGatewayModelUsageResult() interface{} {
	return echofarmrpc.NewEchoFarmGatewayModelUsageResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Health(ctx context.Context, request *echofarmrpc.RelayRequest) (r *echofarmrpc.RelayResponse, err error) {
	var _args echofarmrpc.EchoFarmGatewayHealthArgs
	_args.Request = request
	var _result echofarmrpc.EchoFarmGatewayHealthResult
	if err = p.c.Call(ctx, "Health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Learn(ctx context.Context, request *echofarmrpc.RelayRequest) (r *echofarmrpc.RelayResponse, err error) {
	var _args echofarmrpc.EchoFarmGatewayLearnArgs
	_args.Request = request
	var _result echofarmrpc.EchoFarmGatewayLearnResult
	if err = p.c.Call(ctx, "Learn", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) NextAction(ctx context.Context, request *echofarmrpc.RelayRequest) (r *echofarmrpc.RelayResponse, err error) {
	var _args echofarmrpc.EchoFarmGatewayNextActionArgs
	_args.Request = request
	var _result echofarmrpc.EchoFarmGatewayNextActionResult
	if err = p.c.Call(ctx, "NextAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ActionResult_(ctx context.Context, request *echofarmrpc.RelayRequest) (r *echofarmrpc.RelayResponse, err error) {
	var _args echofarmrpc.EchoFarmGatewayActionResultArgs
	_args.Request = request
	var _result echofarmrpc.EchoFarmGatewayActionResultResult
	if err = p.c.Call(ctx, "ActionResult", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Correction(ctx context.Context, request *echofarmrpc.RelayRequest) (r *echofarmrpc.RelayResponse, err error) {
	var _args echofarmrpc.EchoFarmGatewayCorrectionArgs
	_args.Request = request
	var _result echofarmrpc.EchoFarmGatewayCorrectionResult
	if err = p.c.Call(ctx, "Correction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PlayerModel(ctx context.Context, request *echofarmrpc.RelayRequest) (r *echofarmrpc.RelayResponse, err error) {
	var _args echofarmrpc.EchoFarmGatewayPlayerModelArgs
	_args.Request = request
	var _result echofarmrpc.EchoFarmGatewayPlayerModelResult
	if err = p.c.Call(ctx, "PlayerModel", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Skill(ctx context.Context, request *echofarmrpc.RelayRequest) (r *echofarmrpc.RelayResponse, err error) {
	var _args echofarmrpc.EchoFarmGatewaySkillArgs
	_args.Request = request
	var _result echofarmrpc.EchoFarmGatewaySkillResult
	if err = p.c.Call(ctx, "Skill", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Memory(ctx context.Context, request *echofarmrpc.RelayRequest) (r *echofarmrpc.RelayResponse, err error) {
	var _args echofarmrpc.EchoFarmGatewayMemoryArgs
	_args.Request = request
	var _result echofarmrpc.EchoFarmGatewayMemoryResult
	if err = p.c.Call(ctx, "Memory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ModelUsage(ctx context.Context, request *echofarmrpc.RelayRequest) (r *echofarmrpc.RelayResponse, err error) {
	var _args echofarmrpc.EchoFarmGatewayModelUsageArgs
	_args.Request = request
	var _result echofarmrpc.EchoFarmGatewayModelUsageResult
	if err = p.c.Call(ctx, "ModelUsage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
